### ISSUE TITLE
Setting callbacks

### ISSUE THREAD

**Issue by daurnimator** [alexcrichton/wasm-bindgen#102]
How does wasm-bindgen implement callbacks from DOM objects. e.g. an `onclick` handler?

How do you prevent memory leaks from the WASM heap as objects are exposed to JS?

**Comment by alexcrichton** [comment]
Thanks for the report! Currently this isn't implemented yet but progress is slowly being made! This is currently tracked at https://github.com/alexcrichton/wasm-bindgen/issues/78
