### ISSUE TITLE
Wondering how you called the custom js function `bar_on_reset` in README.md

### ISSUE THREAD

**Issue by adiba** [alexcrichton/wasm-bindgen#17]
You are calling this function located in `index.js` from Rust:
```js
export function bar_on_reset(s, token) {
  console.log(token);
  console.log(`this instance of bar was reset to ${s}`);
}
```
which would mean that the generated js module would have to import `index.js`?

**Comment by adiba** [comment]
yes this is actually true..

**Comment by adiba** [comment]
So can I pass my `index.js` to `wasm-bindgen` as well?

**Comment by adiba** [comment]
Currently exporting my function to `window`

**Comment by alexcrichton** [comment]
Ah yeah so in the README it looks like:

```rust
#[wasm_bindgen(module = "./index")] // what ES6 module to import from
extern {
    fn bar_on_reset(to: &str, opaque: &JsValue);
}
```

which means that the `bar_on_reset` function is imported from `./index.js` (or whatever the bundler resolves that to) If the `module = ".."` is omitted then it's pulled from the ambient environment, like `alert`

**Comment by adiba** [comment]
Oh I'm sorry, oversaw that part. Thank you!
