### ISSUE TITLE
Support for directly importing builtin Web APIs

### ISSUE THREAD

**Issue by lukewagner** [alexcrichton/wasm-bindgen#22]
It would be neat if the developer could put a bindgen annotation on function imports that said "import the JS function found at "x.y.z" (i.e., a sequence of JS property accesses, explicitly starting at the JS global object).  This could allow a dev to import, e.g. `console.log` directly.  Without this support, I think one would have to write a dummy ES Module that exports a function that calls `console.log`.  With this support, one could write a whole DOM-accessing app entirely in Rust.

**Comment by alexcrichton** [comment]
I think this may actually already be possible, albeit in a weird manner:

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(static = console)]
    fn log(s: &str);
}
```

I think though I'd like to also enable something like:

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(static = console, name = "log")]
    fn console_log(s: &str);
}
```

**Comment by alexcrichton** [comment]
Or rather, this is confirmed to work!

```rust
#![feature(proc_macro)]
#![allow(bad_style)]

extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern {
    type console;

    #[wasm_bindgen(static = console)]
    fn log(s: &str);
}

#[wasm_bindgen]
#[no_mangle]
pub extern fn run() {
    console::log("hello!");
}
```

**Comment by alexcrichton** [comment]
although whether it *should* work that way is another question...

**Comment by lukewagner** [comment]
Ah hah, I hadn't seen `static`, cool.  What about things like methods on DOM prototypes, say `Node.prototype.contains`? Another useful one is importing DOM getters and setters; these don't have a simple JS access paths; the glue needed would be of the form: `Object.getOwnPropertyDescriptor(Node.prototype, 'firstChild').get`; it seems like saying `getter` in the attribute, given the path and property name would be sufficient to generate this glue.

**Comment by alexcrichton** [comment]
Oh right yeah good point about properties! I opened up https://github.com/alexcrichton/wasm-bindgen/issues/24 to hopefully track that.

For methods like `contains` you should be able to do:

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen]
    type Node;

    #[wasm_bindgen(method)]
    fn contains(this: &Node, other: JsValue) -> bool;
}
```

and in JS that generates `Node.prototype.contains.call(...)` whereas in Rust it allows you do to `node.contains(...)`

**Comment by alexcrichton** [comment]
@lukewagner to confirm my own JS knowledge (which is quite lacking) though, codgen'ing a method on the JS side is it best to do `Node.prototype.contains.call(...)`? Similarly for properties is it "most accepted" to do things like `Object.getOwnPropertyDescriptor(Node.prototype, 'firstChild').get` or just `foo.get`?

**Comment by lukewagner** [comment]
Ah hah, so `static` vs. `method` determines whether there is an extra `.prototype`; that makes sense.  For `static`, can you pass a dotted property path (e.g., `#[wasm_bindgen(static = WebAssembly.Module)]` to access the static `imports` method)?  If so, then I think we're in great shape.

> @lukewagner to confirm my own JS knowledge (which is quite lacking) though, codgen'ing a method on the JS side is it best to do Node.prototype.contains.call(...)? Similarly for properties is it "most accepted" to do things like Object.getOwnPropertyDescriptor(Node.prototype, 'firstChild').get or just foo.get?

For both those cases, what I'm imagining is that we're actually loading the function to be `.call()`ed once in the generated glue module's top-level script and storing it in a module-level `const` and then the glue always just a `foo.call()`.  The two reasons I can see for this:
* it'll be a bit faster by removing, from every call of the stub, the property lookups and guards and ensure the most optimized call path since the callsite is immutably monomorphic
* it will match what I imagine will be the import semantics of standard Host Bindings: the way wasm instantiation works is the `Instance` is given function values which it stores in a tuple and calls when the wasm import is called; methods and getters would likely be no different.  This is semantically visible if a method gets mutated at runtime.

Given this, the only point of the `getOwnPropertyDescriptor` is to get something that can be stored in a `const` and later `.call()`ed.

**Comment by alexcrichton** [comment]
Aha that all makes sense to me! I've [opened an issue](https://github.com/alexcrichton/wasm-bindgen/issues/26) for dotted properties in the `static =` annotation (not currently supported) as well as https://github.com/alexcrichton/wasm-bindgen/issues/25 for loading everything into a `const` to `.call` rather than doing property lookups each time. Thanks for the info!
