### ISSUE TITLE
JS getters and setters

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/wasm-bindgen#24]
Right now there's no way to set a property on an imported JS object, and this should be added!

Current thinking of how to do this:

```rust
#[wasm_bindgen]
extern {
    type Foo;

    #[wasm_bindgen(getter)] // field inferred via method name, could also be explicit here
    fn foo(this: &Foo) -> u32; // required to have only one `this` argument

    #[wasm_bindgen(setter)]
    fn set_foo(this: &Foo, val: u32); // no return type allowed
}
```

generating JS that looks like:

```js
const foo_get = Object.getOwnPropertyDescriptor(Foo.prototype, 'foo').get;
export function foo_get_shim(idx) {
    return foo_get.call(getObject(idx));
}

const foo_set = Object.getOwnPropertyDescriptor(Foo.prototype, 'foo').set;
export function foo_set_shim(idx, val) {
    return foo_set.call(getObject(idx), val);
}
```

## Previous strawman

I'm not really sure how to model this in Rust's syntax well, but something like this is always an option

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(properties(foo: u32, bar: String))]
    type Foo;

    #[wasm_bindgen(properties(foo(getter): String))] // no setter? .. needs better syntax
    type Bar;
}
```

**Comment by alexcrichton** [comment]
In Rust this would probably want to generate:

```rust
impl Foo {
    pub fn foo(&self) -> FieldType;
    pub fn set_foo(&mut self, val: FieldType);
}
```

**Comment by alexcrichton** [comment]
Oh actually I think @lukewagner's idea in https://github.com/alexcrichton/wasm-bindgen/issues/22#issuecomment-365491451 is way better:

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(properties(foo: u32, bar: String))]
    type Foo;

    #[wasm_bindgen(getter)] // field inferred via method name, could also be explicit here
    fn foo(this: &Foo) -> u32; // required to have only one `this` argument

    #[wasm_bindgen(setter)]
    fn set_foo(this: &Foo, val: u32); // no return type allowed
}

**Comment by lukewagner** [comment]
Nice!  Is the `properties(foo: u32, bar: String)` in the `type Foo` annotation to help out the macro or is it essentially necessary?  I was wondering if the set of properties and their types could be inferred from analyzing the `getter`/`setter`-annotated methods in the extern block.

**Comment by alexcrichton** [comment]
Oh oops, that was a copy/paste error, fixed now! Just dealing with functions and getter/setter annotations should be plenty

**Comment by lukewagner** [comment]
\o/

**Comment by alexcrichton** [comment]
Ok I updated the original post as well with the `getOwnPropertyDescriptor` business as I understand it as well

**Comment by alexcrichton** [comment]
added in https://github.com/alexcrichton/wasm-bindgen/commit/9183236522723b198cdb993225b205f0225af543
