### ISSUE TITLE
Cannot resolve dependency 'env'

### ISSUE THREAD

**Issue by Marwes** [alexcrichton/wasm-bindgen#28]
```
×  try_gluon\src\client\gluon_wasm_wasm.js:2:38: Cannot resolve dependency 'env'
  1 | 
> 2 |             import * as import_b from 'env';import * as import_c from './gluon_wasm';
```

After going through the steps in the README I am currently stuck at the above error. Apparently the code generated from `wasm2es6js` expects an `env` module but I don't get where that is supposed to come from?

**Comment by alexcrichton** [comment]
Thanks for the report! Is this perhaps due to a wasm-bindgen unknown import? Currently the `wasm2es6js` tool assumes that the wasm input module is supposed to be interpreted as an ES6 module, but most wasm files produced by rustc right now aren't as there's not module named `env`.

Would this perhaps be shareable?

**Comment by Marwes** [comment]
The error itself should be reproducible from this branch https://github.com/Marwes/try_gluon/tree/wasm, just run `wasm.sh` (and make sure that https://github.com/ssuman/parcel-plugin-elm is installed.)

**Comment by s3bk** [comment]
I have seen it with mathematical functions. It can be solved by adding them to the import:
```
const importObject = {
    "./bullet_wasm": {
        __wbindgen_throw: function(ptr, len) {
            throw new Error(getStringFromWasm(ptr, len));
        }
    },
    "env": {
        cos: Math.cos,
        sin: Math.sin,
        exp: Math.exp,
        log: Math.log
    }
}
```

**Comment by alexcrichton** [comment]
Aha thanks for the hint @s3bk! Also thanks for the source @Marwes!

I've confirmed that the imports in @Marwes's wasm module are:

```
  (import "env" "Math_acos" (func (;0;) (type 9)))
  (import "env" "Math_atan" (func (;1;) (type 9)))
  (import "env" "Math_atan2" (func (;2;) (type 11)))
  (import "env" "Math_cbrt" (func (;3;) (type 9)))
  (import "env" "Math_cosh" (func (;4;) (type 9)))
  (import "env" "Math_expm1" (func (;5;) (type 9)))
  (import "env" "Math_hypot" (func (;6;) (type 11)))
  (import "env" "Math_log1p" (func (;7;) (type 9)))
  (import "env" "Math_sinh" (func (;8;) (type 9)))
  (import "env" "Math_tan" (func (;9;) (type 9)))
  (import "env" "Math_tanh" (func (;10;) (type 9)))
  (import "env" "__wbindgen_throw" (func (;11;) (type 3)))
  (import "env" "cos" (func (;12;) (type 9)))
  (import "env" "exp" (func (;13;) (type 9)))
  (import "env" "exp2" (func (;14;) (type 9)))
  (import "env" "fma" (func (;15;) (type 14)))
  (import "env" "log" (func (;16;) (type 9)))
  (import "env" "log10" (func (;17;) (type 9)))
  (import "env" "log2" (func (;18;) (type 9)))
  (import "env" "pow" (func (;19;) (type 11)))
  (import "env" "round" (func (;20;) (type 9)))
  (import "env" "sin" (func (;21;) (type 9)))
```

which is certainly something wasm-bindgen could handle! Ideally it wouldn't need to but I see no harm in fixing this for now.

**Comment by Marwes** [comment]
Installed https://github.com/alexcrichton/wasm-bindgen/commit/d66bc257499f4996920eb3fd42db139e92ff0c0e and I now get the WASM running! Running it results in an index out of bounds exception however so I am trying to get source maps working to find out why that is.
