### ISSUE TITLE
Returning Custom Struct 

### ISSUE THREAD

**Issue by rylev** [alexcrichton/wasm-bindgen#29]
I have a simple Rust program (compiled as wasm) that is attempting to interface with JS:
```rust
#![feature(proc_macro)]

extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct MyStruct {
    my_property: usize
}

#[wasm_bindgen]
#[no_mangle]
pub extern fn my_function() -> MyStruct {
    MyStruct { my_property: 1 }
}
```

I then run the following:
```bash
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen target/wasm32-unknown-unknown/release/wasm_test.wasm --out-dir dist
```

And I get the following error:
`thread 'main' panicked at 'no entry found for key', libcore/option.rs:917:5` 

This happens when the wasm-bindgen-cli tool is running. 

I poked around and found that the panic comes from [here](https://github.com/alexcrichton/wasm-bindgen/blob/master/crates/wasm-bindgen-cli-support/src/js.rs#L893) after being called [here](https://github.com/alexcrichton/wasm-bindgen/blob/master/crates/wasm-bindgen-cli-support/src/js.rs#L1194). It seems that the `custom_type_names` hash table is not populated. I then found the JSON that is being stored in the `.wasm` file: 
`{"exports":[{"class":null,"method":false,"function":{"name":"my_function","arguments":[],"ret":"򷟒"}}],"imports":[],"custom_type_names":[]}`.

Two things that don't make sense to me: 
* It's hard to see here but the value in `"ret"` is actually `\u{b77d2}`. 
* The `custom_type_names` array is empty, but I'm guessing that should somehow reference the `MyStruct` struct.

I attempted to dive into the code-gen aspect of bindgen but I got lost. Any ideas?

**Comment by rylev** [comment]
Hmmm... After running `cargo update` this now magically works... Any light on why this was happening so I can understand the code base better would be appreciated. Otherwise, sorry for the false alarm :-D

**Comment by alexcrichton** [comment]
Ah yeah I think this was fixed quite recently, glad the update works though!
