### ISSUE TITLE
Support for returning Vec<JsValue>

### ISSUE THREAD

**Issue by rylev** [alexcrichton/wasm-bindgen#33]
Returning a `JsValue` works and returning `Vec` or `String` works, but returning a `Vec<JsValue>` does not, failing with: `the trait wasm_bindgen::convert::WasmBoundary is not implemented for std::vec::Vec<wasm_bindgen::JsValue>`. I don't see a reason why returning a `Vec<JsValue>` shouldn't work.

I would also be interested in implementing this, but I'm getting lost in the code generation.

**Comment by alexcrichton** [comment]
Hm yeah seems plausible to me! Unfortunately the support for vectors right now is pretty special cased so this may not be easy to do. I suspect this may be best done with some refactoring of the way vectors are supported but it's also fine to implement this directly for now.
