### ISSUE TITLE
How this crate positions itself against stdweb?

### ISSUE THREAD

**Issue by rylev** [alexcrichton/wasm-bindgen#37]
It seems that [stdweb](https://github.com/koute/stdweb) aims to do a lot of the same things wasm-bindgen does (and some more). How is this crate positioned against stdweb? Is it a strict competitor (i.e. more choice, the better) or does it aim to be something different?

**Comment by alexcrichton** [comment]
I think that they're both targeted at making interop with JS through wasm to be nicer, although from my understanding they're taking different approaches and are intended for different use cases. With wasm-bindgen in particular the vision at least is to be a tool that *any* language can use, not just Rust. Ideally C++/other wasm languages would converge on a similar standard so there's only one wasm-bindgen tool and each language compiles down to the tool's intended interface.

In any case I think for now it's great to have multiple options, and we can see where wasm goes!
