### ISSUE TITLE
[Question] Can I pass Promise between JS and Rust by wasm-bindgen?

### ISSUE THREAD

**Issue by y-ich** [alexcrichton/wasm-bindgen#41]
Hi.
I have a question.

I want to call a wasm(Rust) function, that uses a JS async function, from JS.
The wasm function should return a Promise because the function uses an async function.
So there seems be two challenges.
1. The wasm(Rust) function must return something that can be converted to JS promise.
2. The JS async function must return  something that can be converted to something like Futures.

Is it possible by wasm-bindgen?
And if possible, I can use a syntax like futures-await in that case?
(Since I have relatively large amount of synchrous codes, I will be happy if I can use the syntax.)

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! Right now there's not a way with wasm-bindgen to deal with closures/promises/etc, unfortunately. You can work with a promise as an opaque object, but work still needs to be done to integrate with closures and such. In that sense we're still a relatively far way out from having integration with something like `Future`

**Comment by y-ich** [comment]
Thank you for your explanations!
I understand and am looking forward to your project!
