### ISSUE TITLE
feature request: automatically target the lib

### ISSUE THREAD

**Issue by ashleygwilliams** [alexcrichton/wasm-bindgen#45]
the final step for running wasm-bindgen is:

```
wasm-bindgen target/wasm32-unknown-unknown/release/<name of lib>.wasm \ --out-dir .
```

it would be easier to use this tool to automate if it automagically knew to look in that directory for a wasm file named with the same name as the crate.

i'm sure i don't know all the details but would that be possible?

**Comment by alexcrichton** [comment]
To make sure I understand, you're thinking that it'd be nice to do:

```
$ wasm-bindgen
```

which would be the equivalent of

```
$ wasm-bindgen target/wasm32-unknown-unknown/relesase/$inferred.wasm --out-dir .
```

right?

**Comment by ashleygwilliams** [comment]
yeah! maybe with the option to still pass the `--out-dir` flag to configure but to default to `.`

**Comment by alexcrichton** [comment]
Seems plausible to me!

**Comment by ashleygwilliams** [comment]
i'm actually gonna close this, if the goal is that we have wasm-pack wrap this - wasm pack already knows the name of the lib and is a better place to take care of this work since it's already reading the cargo toml. see https://github.com/ashleygwilliams/wasm-pack/pull/17 for details (sorry in advance its a big one)
