### ISSUE TITLE
Should #[no_mangle] and extern be required?

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/wasm-bindgen#46]
Right now when you want to export a function to JS it looks like:

```rust
#[wasm_bindgen]
#[no_mangle]
pub extern fn foo() {
    // ...
}
```

but should the `#[no_mangle]` and `extern` be required? The original thinking was that one day the `#[wasm_bindgen]` attribute could be removed and this'd just reflect what rustc does under the hood already, but I'm getting less and less certain that'll be the case (aka custom types and `&str` probably "won't ever work" in terms of being the right ABI).

It'd certainly be a little easier on the eyes to remove those two components!

**Comment by ashleygwilliams** [comment]
i think it's an interesting question. i think the main question here is:

 "do these signifiers help the reader understand the intent of the code or are they cluttering boilerplate?" 

i haven't written enough code that uses this to have a strong feeling. i am surprised to hear that you might remove the `#[wasm_bindgen]` attribute as i think that that *does* help signify what you want exported in the wasm library.

on my end with [`wasm-pack`](https://github.com/ashleygwilliams/wasm-pack) the `extern`, as well as the 2 attributes, `#[wasm_bindgen]` and `#[no_mangle]` will need to be manual steps that the user takes before being able to use the tool. ergonomics-wise, if those manual steps are truly boilerplate and NOT something that can be opinionatedly done by an author, i would favor eliminating them.

excited to hear from any authors who likely have a better sense of the ergonomics needed here.

**Comment by icefoxen** [comment]
I'd feel that `#[wasm_bindgen]` could easily imply `#[no_mangle]`, since there's probably no situation where you'd want `#[wasm_bindgen]` with mangling enabled.

`extern` I'm a little more ambivalent about, since it seems a more fundamental statement.  You are telling the programmer, not just the compiler, "this is an FFI entry point".

I suppose my question is, what happens when you have a library you want to expose bindings for via `wasm-bindgen`, and also through a different FFI mechanism such as a C?  Or just as a Rust crate?  I dunno, I've only played with `wasm-bindgen` a very little.

**Comment by s3bk** [comment]
My current interpretation is that `#[wasm_bindgen] instructs wasm_bindgen to generate bindings for that function. This would be orthogonal to other attributes, as it is free to inject additional functions that do the translation.
If one wants direct control over FFI, they can still do this with types directly supported by wasm.

In the long run, we probably need module support in wasm_bindgen that reflects in the JS bindings.
This means that `#[no_mangle]` is not really the best choice.

**Comment by alexcrichton** [comment]
Yeah I'm sort of feeling like the case for removing `#[no_mangle]` is pretty strong, although I'm less certain of `extern`. I do think it's probably a natural extension as it's sort of an obscure implementation detail that doesn't actually have any relevance to the API that's generated. The wasm-bindgen macro is the one that's actually in control of the ABI anyway!

So in that sense I'm leaning towards relaxing the requirement and removing the need for both of these.

**Comment by dignifiedquire** [comment]
👍 for removing both of these. Currently when writing the code they seem superfluous, as `#[wasm-bindgen]` is already indicating everything I need to know about the importance of the construct being annotated.

**Comment by alexcrichton** [comment]
Ok I think I'm pretty certain at this point it's a good idea to drop both requirements!

I'm gonna tag this as a "good first issue" for anyone interested, the relevant sections I believe are:

* [Here's where we require `#[no_mangle]`](https://github.com/alexcrichton/wasm-bindgen/blob/644e96cd462ddce3be9c068425b1776df7194d53/crates/wasm-bindgen-macro/src/ast.rs#L87-L97), and I think that can mostly be removed although we should still filter out the `#[no_mangle]` attribute. Then the tests in `tests/*.rs` can be updated to remove the attribute!
* The `extern` requirement [is around here](https://github.com/alexcrichton/wasm-bindgen/blob/644e96cd462ddce3be9c068425b1776df7194d53/crates/wasm-bindgen-macro/src/ast.rs#L383-L386) and can also probably just get deleted, and then the tests can be updated as well!
