### ISSUE TITLE
hello_world example gives "WebAssembly.Instance is disallowed" in Chrome

### ISSUE THREAD

**Issue by sophiebits** [alexcrichton/wasm-bindgen#50]
Heya! I just tried to run the hello_world example on my machine (rustc 1.26.0-nightly (9cb18a92a 2018-03-02), wasm-bindgen master today 98b9bee876, Mac Chrome) and it throws the error:

> RangeError: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.

which appears to directly result from the generated `import * as wasm from './hello_world_wasm';` line. I found https://github.com/webpack/webpack/issues/6475 implying this is a browser limitation of sync wasm instantiation and https://github.com/alexcrichton/wasm-bindgen/issues/39 where you briefly discuss this issue, but from your comments it sounds like *async* import causes this error, not the *sync* import which is what I'm seeing.

Any chance you can point me in the right direction? Not sure if it's user error. :)

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is indeed basically due to https://github.com/webpack/webpack/issues/6475 which happens regardless of whether it's a sync or async import. In the meantime you'll want to use Firefox (which has a higher limit) or the `wasm2es6js` tool in this repository which is a hack to translate a wasm file into a JS ES6 module (and doesn't use `new WebAssembly.Instance`). 

I had forgotten about this bug though, and it should definitely be mentioned in the README!

Would probably also be good to add a script which use the `wasm2es6js` hack.

**Comment by sendilkumarn** [comment]
I believe it happens only on sync imports and for async imports it doesnt matter. 

As the webpack/webpack#6475 suggests can try using modules ?

**Comment by sophiebits** [comment]
On my machine I just confirmed that using import() still compiles to `new WebAssembly.Instance` and throws the same error.

**Comment by dignifiedquire** [comment]
Running into the same issue, I tried using https://github.com/ballercat/wasm-loader to work around, which now throws this fun error: 

```
ERROR in ./cryptasm_wasm.wasm
Module parse failed: WasmCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 76 61 72 20 @+0
You may need an appropriate loader to handle this file type.
CompileError: WasmCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 76 61 72 20 @+0
    at WebAssemblyParser.parse (/Users/dignifiedquire/opensource/cryptasm/node_modules/webpack/lib/WebAssemblyParser.js:31:16)
    at doBuild.err (/Users/dignifiedquire/opensource/cryptasm/node_modules/webpack/lib/NormalModule.js:367:32)
    at runLoaders (/Users/dignifiedquire/opensource/cryptasm/node_modules/webpack/lib/NormalModule.js:264:12)
    at /Users/dignifiedquire/opensource/cryptasm/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/dignifiedquire/opensource/cryptasm/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/dignifiedquire/opensource/cryptasm/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/dignifiedquire/opensource/cryptasm/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at Object.context.callback (/Users/dignifiedquire/opensource/cryptasm/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/dignifiedquire/opensource/cryptasm/node_modules/wasm-loader/index.js:34:8)
    at LOADER_EXECUTION (/Users/dignifiedquire/opensource/cryptasm/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
 @ ./cryptasm.js 3:12-52 18:49-60 19:55-66 28:32-54 50:32-41 52:32-61 53:32-61 55:20-50 60:0-20 66:28-50 81:32-47 83:32-61 84:32-61 86:20-50 91:0-20 93:0-20 95:0-20
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js
```

with the default config of that loader

**Comment by xtuc** [comment]
@dignifiedquire that is strange,  the wasn't binary is not valid anymore. 

Did you run wasm2es6js?

**Comment by dignifiedquire** [comment]
not yet, will try with that

**Comment by xtuc** [comment]
Your bug is probably not related, it seems that your binary is not a valid wasm one (doesn't look like text either). 

How did you generate the binary?

**Comment by dignifiedquire** [comment]
as described in the readme, cargo build && wasm-bindgen

**Comment by xtuc** [comment]
Ok, I can't help here sorry.  Maybe @alexcrichton has an idea why the header is invalid.

**Comment by alexcrichton** [comment]
@dignifiedquire hm I'm not sure if wasm-loader would be too applicable here as the idea behind this project is that wasm file is just another es6 module, but interpreting it as such requires bundler support (aka the support that Webpack 4.0 has added).

I'm not entirely sure how that works though or where the header is coming from :(
