### ISSUE TITLE
Support for native modules in generated JS

### ISSUE THREAD

**Issue by LucasHill** [alexcrichton/wasm-bindgen#67]
It could be nice to have an option where the generated JS does not depend on webpack. The primary issue is the import statement of the wasm file I think? Since this project implicitly targets browsers that support wasm, this mostly overlaps also with browsers that support native modules.

**Comment by RReverser** [comment]
Indeed. Even if not targeting browsers with native module support, it was quite surprising to discover that `--nodejs` does not actually emit Node.js-compatible code, but rather Webpack+Node.js compatible code (there is no reason not to emit CommonJS when that parameter is used).

**Comment by alexcrichton** [comment]
Thanks for the report! The intention of wasm-bindgen is very much to not require webpack! It just so happens that Webpack is the only bundler (AFAIK) right now that treats wasm modules as ES modules (and has enough implemented to work with wasm-bindgen), so it was the example shown in the README. That being said it's not required to use Webpack, you can instantiate the ES modules that is the wasm module however you'd like!

@LucasHill did you have a particular use case and/or bundler in mind though?

**Comment by LucasHill** [comment]
@alexcrichton My project is just a toy app that I had planned on writing in vanilla javascript with native es modules using the module loader in the browser rather than a bundler. I think all the major browsers except firefox support that now.

Just taking a look at what webpack is doing is it appears to convert the import statement into a fetch and then using the WebAssembly API (WebAssembly.compileStreaming) to load the wasm file. Is loading wasm using the import syntax a future native thing you can do or just a webpack feature? Seems this project could just emit JS that uses the WebAssembly API rather than using the import syntax, eliminating the need for webpack or another bundler.

Anyway, loving this project, thanks for making it.

**Comment by alexcrichton** [comment]
Ah yeah unfortunately wasm modules are not currently hooked up as ES modules, but the tracking issue for that is https://github.com/WebAssembly/design/issues/1087

**Comment by alexcrichton** [comment]
I'm gonna close this for now as I believe this is natively done/supported right now, but if there's more questiosn please feel free to let me know!

**Comment by ForsakenHarmony** [comment]
Can't we do this without the es modules?
