### ISSUE TITLE
Passing Rust struct ownership into JS

### ISSUE THREAD

**Issue by Healthire** [alexcrichton/wasm-bindgen#69]
Currently you can't pass ownership of a rust struct from rust to JS through an import, like this:
```rust
#[wasm_bindgen]
struct Foo();

#[wasm_bindgen]
extern {
    fn take_struct(foo: Foo);
}
```
but you can return it from an exported function:
```rust
#[wasm_bindgen]
fn create_foo() -> Foo {
    Foo()
}
```
Is this a conscious style choice or is passing in structs by value just not implemented yet?

In both cases js takes ownership of the object and becomes responsible for freeing it if it's dropped. But I can see that being clearer when the object is a return from a rust export, than when receiving an object as an argument from rust.

**Comment by alexcrichton** [comment]
Oh oops I think that's an oversight! I think this definitely makes sense to support

**Comment by alexcrichton** [comment]
Added in https://github.com/alexcrichton/wasm-bindgen/pull/70
