### ISSUE TITLE
How can I get a reference to the `document` object?

### ISSUE THREAD

**Issue by akritrime** [alexcrichton/wasm-bindgen#71]
On js side, `document` or rather `window.document` provides the reference to the `document` object contained in the current window. Is there any way I can access that document using wasm_bindgen? Or do I need to write a js file exposes the required functionality of the document API?

**Comment by alexcrichton** [comment]
A good question!

This wasn't actually super easy to do before so I've been thinking a bit and have decided to tweak how some functions are accessed exposed. I've now written up an [example](https://github.com/alexcrichton/wasm-bindgen/commit/dd054fa357862c84ef9a83fb8fd953a449da79ed) of how to do this as well!

For now that functionality is only available on master, but I'll publish 0.2 soon with that!

**Comment by alexcrichton** [comment]
Please let me know though if the example is confusing or otherwise needs to be fleshed out more, I'd love to expand it!

**Comment by akritrime** [comment]
@alexcrichton That example is quite enough. One doubt though, why can't `JsValue` be used instead of a new type of HTMLDocument?

**Comment by alexcrichton** [comment]
Ah currently this is just the main way to add methods to an otherwise "bland `JsValue`", but internally it's just a `JsValue` so I pushed up https://github.com/alexcrichton/wasm-bindgen/commit/fc81d8f6d39a566976ee27c2811aaa08f285f827 which allows interconversion
