### ISSUE TITLE
Can the size of the generated wasm be reduced? 

### ISSUE THREAD

**Issue by akritrime** [alexcrichton/wasm-bindgen#73]
Currently wasm binary for even this simple function 
```rust
#![feature(proc_macro)]

extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn run(x: i32, y: i32) -> i32 {
    x + y
}
``` 
is 230kb, after applying wasm-gc.

**Comment by alexcrichton** [comment]
Thanks for the report! Are you also compiling with LTO and optimizations?

**Comment by akritrime** [comment]
Actually no, I thought --release had LTO enabled by default. And LTO brought it down to 10 kb. Should I close this issue?

**Comment by markandrus** [comment]
@alexcrichton would you consider extending the "Basic Usage" example to run `wasm-gc`, `wasm-opt`, and/or whatever `wasm-bindgen` flags (LTO? `--release`?) are required to achieve the minimum file size?

**Comment by markandrus** [comment]
Here are steps that worked for me:

1. Build with `--release`

  ```
  cargo build --release --target wasm32-unknown-unknown
  ```

2. Run `wasm-bindgen`

  ```
  wasm-bindgen target/wasm32-unknown-unknown/release/js_hello_world.wasm --out-dir .
  ```

3. Run `wasm-gc`

  ```
  wasm-gc js_hello_world_bg.wasm js_hello_world_bg_gc.wasm
  ```

4. Run `wasm-opt`

  ```
  wasm-opt js_hello_world_bg_gc.wasm -Os -o js_hello_world_bg_gc_opt.wasm
  ```

Then, update `js_hello_world.js` to import `js_hello_world_bg_gc_opt`.

```
$ wc -c <js_hello_world_bg.wasm
  237298
$ wc -c <js_hello_world_bg_gc.wasm
  227057
$ wc -c <js_hello_world_gc_gc_opt.wasm
  167750
```

**Comment by csharad** [comment]
You could reduce the file size much more. Add the following to `Cargo.toml` and do `cargo build --release`.  
```
[profile.release]
lto = true
```

**Comment by alexcrichton** [comment]
@markandrus thanks for the report!

This is definitely a general problem of "we need documentation about generating the smallest binaries". I've opened an issue at https://github.com/rust-lang-nursery/rust-wasm/issues/109 for documenting this in the working group's book

**Comment by markandrus** [comment]
Thanks for the tips, y'all!

With `lto = true` (and the same sequence of transformations), I get

```
$ wc -c <js_hello_world_gc_opt.wasm
   43513
```

If I add `opt-size = 'z'`, it gets even smaller:

```
$ wc -c <js_hello_world_gc_opt.wasm
   36128
```

Using `wee_alloc` and `std`,

```
$ wc -c <js_hello_world_gc_opt.wasm
   32294
```

I dont think `no_std` is an option—at least for the "Basic Usage" example, since it uses `format`—so I'm not sure it can go smaller?

**Comment by alexcrichton** [comment]
@markandrus the "hello world" example uses string formatting and allocation which are two major contributors to code size. Projects focused on code size tend to avoid at least string formatting and often allocations, so the "hello world" isn't necessarily representative of what a hello-world would look like for a size-concerned application

**Comment by alexcrichton** [comment]
@michael8090 I think you're likely running up against "string allocation and panicking is large in rust right now", which while hopefully reduced on the next successful nightly isn't necessarily directly related to wasm-bindgen.

**Comment by Hywan** [comment]
I'm trying to compile wasm-bindgen with `no_std` too, and I got this error:

```
error[E0433]: failed to resolve. Did you mean `nom::lib::std`?
 --> src/wasm.rs:6:1
  |
6 | #[wasm_bindgen(module = "./parser_definitions")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean `nom::lib::std`?
```

It tries to find another libstd somewhere in another crate (here, nom).

Is it possible to compile wasm-bindgen with `no_std`?

**Comment by alexcrichton** [comment]
Ah currently the macro can only be used in crates that have `std` at the root, but I'd love to fix that! Nothing inherently requires std here (but passing things like `String` does). @Hywan want to open a dedicated issue for that?

**Comment by Hywan** [comment]
Sure, done.

**Comment by sophiebits** [comment]
I'm having trouble getting a minimal-size setup. My intent was to try to make a small demo module that adds two numbers and build up from there but it's not easy for me to understand the combination of incantations for lto, opt-size, wasm-opt, no_std (I think), no allocator, no formatting (wasm-snip?) that I need. Would it be possible to get an example added to the repo showing the smallest known possible wasm-bindgen output that can be used as a starting point for size-conscious libraries?

**Comment by alexcrichton** [comment]
@sophiebits sure yeah! I just added a [new example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/add) which you can also [play around with online](https://webassembly.studio/?f=612vwsrmwft). 

The key things for "simple code" (aka adding numbers) is to enable LTO and to compile with optimizations. That's set by wasm-bindgen's [workspace](https://github.com/rustwasm/wasm-bindgen/blob/947386ee571bdacbe4f62b0f4dd9205b2b8f015f/Cargo.toml#L44-L47) currently.

For a bit larger of an example I've seen the [dom example](https://github.com/rustwasm/wasm-bindgen/tree/947386ee571bdacbe4f62b0f4dd9205b2b8f015f/examples/dom) is also quite small in the compile wasm size, which you can also [explore online](https://webassembly.studio/?f=54xnz04tcke) as well. 

If you're wondering about a particular piece of code though and how to get it smaller just let me know! I'd love to help out and see what we can improve in the libraries/tooling along the way.

**Comment by alexcrichton** [comment]
Hm odd! When I compile the `dom` example with `--release` I get a 1.5k wasm file coming out of `wasm-bindgen` and 632 bytes after `wasm-opt`.

@sophiebits are you sure you're compiling with LTO though? When I turn off LTO and `opt-level = 's'`  the output of `wasm-bindgen` jumps to 217k and the `wasm-opt` optimized size is 161k. If not though, have some code I could poke around and try to reproduce with?

**Comment by sophiebits** [comment]
Ahh. I was testing in the repo directly (having edited your build.sh) but I neglected to update "debug" to "release" in the path ../../target/wasm32-unknown-unknown/release/dom.wasm. I get what you get now!

**Comment by alexcrichton** [comment]
Heh I've done that more than once before as well :)

**Comment by ttraenkler** [comment]
Great to see the dramatic reduction of the add example to 600 bytes! What is still in the module? In comparison, IIRC the add example in AssemblyScript is only 80 bytes, so maybe there is still room for improvement?
