### ISSUE TITLE
Implement `WasmBoundary` for types like String/Vec/str

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/wasm-bindgen#87]
@fitzgen and I had a fantastic discussion just now about how to implement the `WasmBoundary` trait for more types. Right now there's a bunch of special casing for vectors, slices, and strings, but that's a bit of a bummer! It'd be best if each type could implement a trait so we could let rustc's name resolution and type resolution figure out what the types are.

This'll be tricky though because types like vectors/slices take *two* arguments in the ABI. I think though we can develop a solution where a call to JS creates a local stack array of values which we then pass to JS. Similarly there'd be one global stack of values for JS to pass to wasm.

The final tricky part is getting signatures *without* strings/vectors to not use the stack (to be optimized more in the engine), but I think we can deal with that at compile time by generating code for both and having rustc optimize which one ends up getting run.

**Comment by fitzgen** [comment]
Note that we don't actually need a whole *stack*, just a single *stack frame*.

**Comment by fitzgen** [comment]
Assuming a maximum function arity, of course.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/wasm-bindgen/commit/cdbb31f3a99463b57a78382911fd6ea3b8abce54
